# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17na1gv-VHUGnFuiFOTsUXx3maoYpL4C-
"""

score = input().split()
count = 0
total = 0
for i in score:
  total = total + int(i)
  count = count + 1
average = total / count
print(average)